apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-readiness-http
spec:
  containers:
  - name: liveness-readiness-http
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 4
      failureThreshold: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 100
      periodSeconds: 10
      timeoutSeconds: 4
      failureThreshold: 2
